### ISSUE TITLE
not work if favicon is not set

### ISSUE THREAD

**Issue by winor30** [zilpay/zil-pay#17]
If `icon ` or `shortcut icon` is not set, zilpay cannot show auth popup because `favicon` is undefined. (following related code)
https://github.com/zilpay/zil-pay/blob/9461cd19e4c4848da9621fdaa3af751270cc9c22/extension/inpage/utils.js#L17-L19

Normally favicon might be set, but I think that someone may not set favicon in especially developing process too.

**Comment by lich666dead** [comment]
hello,thanks for it issues, i think about if in your dApp does't have ```favicon``` ZilPay is not show popup window. Something like a quality standard but I can revise this rule and correct it in the new version.

**Comment by lich666dead** [comment]
Fixed in this commit: https://github.com/zilpay/zil-pay/commit/eeed7ace78963b36efa5aec02657d82f1d331c4b
