### ISSUE TITLE
ZIL token missing in Wallet (Testnet)

### ISSUE THREAD

**Issue by SvenMeyer** [zilpay/zil-pay#20]
Yesterday Zilpay showed my Test ZILs , today it shows zero and no history. I checked multiple times that Zilpay is on Testnet, logged out and in again , still 0 ZIL and no transaction history.
Blockchain explorer (of course) shows everything is still there.

[https://viewblock.io/zilliqa/address/zil1pw587sm57lvlu0wlwkc3gw2sddy35au6esw589?network=testnet](https://viewblock.io/zilliqa/address/zil1pw587sm57lvlu0wlwkc3gw2sddy35au6esw589?network=testnet)

What's wrong ?
![Screenshot ZilPay testnet account](https://user-images.githubusercontent.com/25609/69707582-25f29e80-114e-11ea-9121-2932ba9d6574.png)

**Comment by lich666dead** [comment]
Hello, yeah this problem have in testnet node url current week.

**Comment by SvenMeyer** [comment]
I just transferred new ZIL from the faucet and moved on from there.
[https://dev-wallet.zilliqa.com/faucet](https://dev-wallet.zilliqa.com/faucet)
