### ISSUE TITLE
Zilpay plugin error on Chrome 80

### ISSUE THREAD

**Issue by SvenMeyer** [zilpay/zil-pay#24]
I saw this error in the plugin/extension section after upgrading to Chrome 80

![Zilpay - Chrome 80 -error](https://user-images.githubusercontent.com/25609/74076475-5f0f8f00-4a6c-11ea-8492-035e62dec7c4.png)

**Comment by lich666dead** [comment]
Hello, thanks for your issue! This problem have when this happens when the headers block access to `WebAssembly` or browser is support it. Module BN use `WebAssembly` for optimization.

**Comment by lich666dead** [comment]
fixed in [0.4.8](https://github.com/zilpay/zil-pay/releases/tag/0.4.8)
