### ISSUE TITLE
When a dapp is connected - wallet.connect() doesn't ask the user to unlock their wallet

### ISSUE THREAD

**Issue by VexyCats** [zilpay/zil-pay#27]
If a wallet is locked - and the user has already connected to the site - then no function called will ask them to unlock their wallet 

If the user is NOT connected to the dapp - calling `wallet.connect()` will ask them to unlock and then let the dapp access their wallet. 

If the user IS connected to the dapp but comes back the next day - nothing can be called to show the wallet unlock screen - so if the dapp requires a wallet unlocked, it will just ask them to unlock it. 

`.connect()` should show "unlock your wallet" even if they are connected already. 

Otherwise there needs to be another function to call when `wallet.isEnabled()` returns false

**Comment by lich666dead** [comment]
Thanks for your issue, i can decide this two variants:

1. Show popup for unlock and confirm or reject connection to website.
2. Throw an error "Wallet has disabled.".

**Comment by VexyCats** [comment]
An error is already thrown when trying to access their wallet but its locked. So thats not helpful as its already happening. 

There needs to be a way to prompt the user to unlock their wallet to continue. We can currently show a modal that says unlock your wallet, but then they need to refresh the page once unlocked. 

Number 1 is the best choice.

**Comment by lich666dead** [comment]
ok, then it will be popup
