### ISSUE TITLE
Transactions not completing + Lost ZIL

### ISSUE THREAD

**Issue by Marmoq** [zilpay/zil-pay#35]
Hello - I've had two different occurrences now where a transaction did not complete on the Zilliqa chain involving the Zilpay wallet funds. 

The first happened when trying to swap in Zilswap, where the ZIL I was trying to swap ended up hanging in the transaction until the tx expired. Supposedly expired transactions don't affect balance aside from fees, but this one took all the ZIL with it.

The second is a transfer from KuCoin. I initiated it some time ago, KuCoin says it was successful, but when I check the ZIlliqa block explorer I just get an "oops your transaction cannot be found" error.

Also, inside of the Zilpay wallet all of my transactions just show as 'Triggered' and they are not flipping over to completed. It's like it's just stuck. Can you help with any of these?

**Comment by hicaru** [comment]
Hello, thanks for your issue! Could you show me your address?

**Comment by Marmoq** [comment]
Yes! zil1dlr5za6szpv2wv7qy4cqn7e3723ge4jc87vhqz

An update for the first part - KuCoin support was able to help me clear up the stuck tx. All is well there now.

But for the second part - Currently all transactions are still showing as Triggered in my Zilpay wallet. Is that behavior that has been identified and is being worked out? Does Zilpay require browser cache clearings or something of that sort? 
<img width="326" alt="Screen Shot 2020-10-07 at 10 55 08 AM" src="https://user-images.githubusercontent.com/72416358/95362655-9ea4aa00-088b-11eb-85e9-fa536f286f89.png">

**Comment by etrolik** [comment]
Hi there, I have the same issue. Transaction pending for a day there is no way to terminate it. I was trying to swap the token with speed at 30 ZIL but I guess priece changed and transaction instead of terminating got stuck in pending status. Can we take the support off-line so I dont need to share addresses publicly. Thanks

**Comment by hicaru** [comment]
hello guys thanks for your details, if you click to Transaction, you can cancel it, or just clear all transactions history via `Clear all`. it can be nonce issue, if you have sent transaction with other wallet, or sent a lot of transactions in one pool

**Comment by etrolik** [comment]
> hello guys thanks for your details, if you click to Transaction, you can cancel it, or just clear all transactions history via `Clear all`. it can be nonce issue, if you have sent transaction with other wallet, or sent a lot of transactions in one pool

Clear all- I persume this will only clear transaction history. I don't see cancel when in the transaction details mode.

**Comment by hicaru** [comment]
> > hello guys thanks for your details, if you click to Transaction, you can cancel it, or just clear all transactions history via `Clear all`. it can be nonce issue, if you have sent transaction with other wallet, or sent a lot of transactions in one pool
> 
> Clear all- I persume this will only clear transaction history. I don't see cancel when in the transaction details mode.
> https://viewblock.io/zilliqa/tx/6d7622de9a81fb9ca1dbb809d3fd36702c45fee666a0ee8196fc088e8c1f3b8a?network=mainnet
> See if this link helps to look at it. I don't see BOLT in my wallet and transaction is still pending in my ZilPay but i can see it here https://viewblock.io/zilliqa/address/zil12vuqlcyaq6xacwdg8w5xp9a0tnnp5qhve8srnp?txsType=token&specific=zil1x6z064fkssmef222gkhz3u5fhx57kyssn7vlu0
> @hicaru
> How do we then transfer from ZilPay to erc20 network?


you can add token `zil1x6z064fkssmef222gkhz3u5fhx57kyssn7vlu0`
![image](https://user-images.githubusercontent.com/21293723/95440598-92dfe300-0972-11eb-910c-4d8310d06817.png)

just add token and select that, after you can transfer this token.

Transactions history need for calculate, current nonce.

**Comment by etrolik** [comment]
> zil1x6z064fkssmef222gkhz3u5fhx57kyssn7vlu0

ok this sorted out my balance !! thanks just testing the wallet. Can you now tell me how to send it out to my ledger now? Send address is looking for zil address or domain so if i use my ethernum address will this get sent to limbo or will it reach my eth ledger wallet?

**Comment by hicaru** [comment]
> > zil1x6z064fkssmef222gkhz3u5fhx57kyssn7vlu0
> 
> ok this sorted out my balance !! thanks just testing the wallet. Can you now tell me how to send it out to my ledger now? Send address is looking for zil address or domain so if i use my ethernum address will this get sent to limbo or will it reach my eth ledger wallet?

you cannot send to ETH address!!! You need install Zilliqa app from ledger store, connect to you PC and import account like:
![image](https://user-images.githubusercontent.com/21293723/95442166-7ba1f500-0974-11eb-9880-b1c190619407.png)
