### ISSUE TITLE
my ZIL lost

### ISSUE THREAD

**Issue by bakpity77** [zilpay/zil-pay#37]
this morning tried to swap GZil to Zil than sending to kucoin using Zipay and Zilswab together. as a recipient address I put my Kucoin address. 

It has never arrived, transaction appears on Ziliqa website.

pls help what to do.

attached as it looks as transaction
![IMG_0978](https://user-images.githubusercontent.com/64318148/97024575-f8140680-1524-11eb-8555-1931273e8021.jpg)

also  i have the two hashes where the money disapperaed.
Can pls someone respond

**Comment by hicaru** [comment]
could you post your transaction hashs and you address

**Comment by hicaru** [comment]
timeout

**Comment by bakpity77** [comment]
Sorry what do you mean closed? Does it mean resolved?

Sent from my iPhone

On Oct 25, 2020, at 11:36 AM, Rinat <notifications@github.com> wrote:

﻿

timeout

**Comment by bakpity77** [comment]
Sorry why is it closed ? My problem has not resolved

**Comment by bakpity77** [comment]
35bb1525eb6689126a282c5ebb554b28c8f338d5a2dd35c04fa00029fc41eb15





75e136a508a1812d8fb51b779e3789826304b75d9ed998186d394fd72cc2b487

**Comment by bakpity77** [comment]
The hashes
