### ISSUE TITLE
Chrome's browsersync and zilpay's no wallet warning

### ISSUE THREAD

**Issue by csajedi** [zilpay/zil-pay#39]
**Is your feature request related to a problem? Please describe.**
I use the plugin with chrome and only have/need the wallet on one of my browser instances. However everytime I open chrome on any other device a tab is opened and zilpay insists I must recover or create a wallet. This message is seen dozens of times a day and is growing unfuriating. There is no way to disable it without disabling the wallet on the one browser instance I actually need. I cannot imagine a good argument for including this notice. When someone needs a zilpay wallet instance they will have a a good enough reason to do it then instead of pestering them about it endlessly across all their devices.

**Describe the solution you'd like**
I don't think this prompt serves any purpose, it should be removed.

**Describe alternatives you've considered**
A way to disable it across all your browser instances seems like it might be impossible without disabling the plugin and losing the wallet instance in the browser installation where you need it.

**Comment by hicaru** [comment]
Hello thanks for your issue, it is bug. This issue will fix in new version of ZilPay wallet. Thanks
