### ISSUE TITLE
Unable verify recovery password with repeated words

### ISSUE THREAD

**Issue by AHaliq** [zilpay/zil-pay#40]
**Describe the bug**
When given a seed with a word repeated, clicking on one word will get rid of both instances of the word.

**To Reproduce**
1. Upon installation of zilpay extension you will be brought to a webpage
2. If the recovery password has more than one instance of a word click next
3. Attempt to verify

**Expected behavior**
Only one instance of the word should disappear when clicking one duplicated word, not both.

**Screenshots**
![image](https://user-images.githubusercontent.com/1249610/103728348-b588a300-5018-11eb-86a2-eba91982c2eb.png)
![image](https://user-images.githubusercontent.com/1249610/103728359-c0433800-5018-11eb-8aa8-579b29c26ab4.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave Version 10.14.6
 - Browser chrome
 - Version 86.0.4240.80 (Official Build) (x86_64)

Note I am not using the recovery password for my wallet so its fine to share it here.

**Comment by hicaru** [comment]
thanks for detail issue i will fix it in new release.
