### ISSUE TITLE
chrome's irritating prompt

### ISSUE THREAD

**Issue by csajedi** [zilpay/zil-pay#41]
**Describe the bug**
this is exactly  issue #39  it is still not fixed and I am about to give up on zilpay.

**Comment by hicaru** [comment]
Could you get me more details about this issue? I cannot implement that bug

**Comment by csajedi** [comment]
Basically I have Chrome installed on 4 OSes across 3 machines. In one case I have the Zilpay wallet configured, on the rest of my Chrome installations I haven't bothered. Anywhere zilpay isnt configured, when I open a new chrome window - just after it loads - a new tab opens and forces focus, which prompts me to setup my wallet. I probably interact with this tab by closing it ~ 20 times per day. Very frustrating.
![image](https://user-images.githubusercontent.com/1924167/106945252-93f10900-66f5-11eb-9a63-dc98eb873bd4.png)

**Comment by hicaru** [comment]
Hmm weird could you disable all other extension and try again?
