### ISSUE TITLE
Rename accounts

### ISSUE THREAD

**Issue by frog357** [zilpay/zil-pay#43]
**Describe the solution you'd like**
I have multiple accounts named Account 1, Account 2, etc. I would like to name them say like: SmartContracts1A, Personal, Testing, etc.  I looked but could not locate how to rename them.

**Comment by hicaru** [comment]
You can rename account, click to `receive` -> `deposit` -> you will see the input with your account name.

**Comment by frog357** [comment]
I tried to change an account name using that input box but there was no
save button and the name does not appear to take effect?

**Comment by hicaru** [comment]
It is autosave

**Comment by frog357** [comment]
I believe the issue was related to the limit of input length, I was using
the name "Unstoppable1" and it would silently not save. I tried a few times
and with a shorter name it finally worked.

Thanks for writing, Take care!

Freddy
www.freddyt.com

**Comment by hicaru** [comment]
ok, thanks for this information, i will increase the max length

**Comment by hicaru** [comment]
fixed in 0.8.5 version
