### ISSUE TITLE
Possible Password Related Bug

### ISSUE THREAD

**Issue by MoJoJay** [zilpay/zil-pay#45]
I'm a new user to your extension, would someone assist me, is this a bug or am i doing something wrong here.

**Issue 1:** Attempting to import a second zil account in to ZilPay.
The KeyStore/JSON file imports but when the password for the JSON file is entered, i get an error.
I've tested the KeyStoreJSON file and password by importing it to zillet.io, and the wallet opens without any issues, why can i not import it in to Zilpay extension.

**Issue 2.** A second password related issue. This time i installed the ZilPay extension for the first time in to 2 browsers. Copied the seed words, created a password. Then conducted a test to see if i had access to all areas of the extension, under security.
Reveal Secret Phrase - password works
Reveal Private Key - password does NOT work
Download Keystore file - password does NOT work. 
Why is this happening?

Finally: you Twitter page says in the header image that the ZilPay app is available on the App Store - with Apple's App store A, logo there, but there is no app on the UK app store.

![Screenshot 2021-03-01 at 17 44 28](https://user-images.githubusercontent.com/3296919/109536565-c94f0380-7ab5-11eb-9fcb-e3c12374adab.png)
![Screenshot 2021-03-01 at 17 45 24](https://user-images.githubusercontent.com/3296919/109536670-eaafef80-7ab5-11eb-93e4-bc23eb35c46e.png)

**Expected behavior**
What i'm was expecting is that for 
Issue 1 - that i could set up a second wallet in my ZilPay extension.
For issue 2 - Why are the passwords not working and why can i not download the zil Keystore/JSON file.....? Would this be related to having some Zil funds in the account?

**Mac (Mac running macOS Catalina 10.15.7.):**
- Current ZilPay Extension - running on Firefox (86.0 64bit) 
- Google - Chrome Version 88.0.4324.192 (x86_64) on two different Mac running macOS Catalina 10.15.7.

**Comment by hicaru** [comment]
Yes, thanks for your issue, this is bug i will fix in new version

**Comment by hicaru** [comment]
About appstore apple doesn't support open source developers, that means apple just remove from appstore ZIlPay. Now Apple wait when i will hand over documents about company
