### ISSUE TITLE
Claim ZilSwap liquidity rewards doesn't work with Ledger hardware wallet

### ISSUE THREAD

**Issue by joeylith** [zilpay/zil-pay#48]
Claim ZilSwap liquidity rewards doesn't work with Ledger hardware wallet. Other transaction types works.

Steps to reproduce:
1. Connect to ZilStream with Ledger imported wallet. Make sure Ledger Nano S wallet is plugged in and Zilliqa app is installed and activated on Ledger.
2. Click on "Claim rewards" button with Rewards Unclaimed value.
3. ZilPay confirm transaction button is displayed. Click "Confirm". 
4. Progress ticker will be shown but no transaction confirmation will be displayed on Ledger Nano S. Expected result is transaction confirmation message to be displayed on Ledger Nano S.
5. ZilPay confirmation screen will be displayed again. No transaction initiated to redeem rewards.

**Comment by joeylith** [comment]
Issue seems to happen with transactions involving Zwap. I tried zilswap transaction for Zwap to Zil and it also didn't work. It works when private key is within ZilPay without Ledger.

**Comment by hicaru** [comment]
hello try another browser
