### ISSUE TITLE
The sign() function for data does not match the reproduction of a signature in scilla or the sdk example

### ISSUE THREAD

**Issue by csajedi** [zilpay/zil-pay#50]
**Describe the bug**
The message sign() function produces a signature that does not pass the verification node.js code at the same place in the documentation, incidentally it also does not pass the on-chain scilla function either.

**To Reproduce**
1. Go to https://zilpay.github.io/zilpay-docs/zilliqa-provider/#sign-message
2. Follow steps
3 . See error

**Expected behavior**
At least I'd hope that the sign method works with the scilla lang, otherwise it is of very little use

**Screenshots**
You can see an example of a sign() produced message being rejected on chain with this transaction https://viewblock.io/zilliqa/tx/0x03fa9b1d3595a7d6aac1cbf5838db9148687c07af894e6eb05accf701f7364ef

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 92

**Comment by hicaru** [comment]
hello please learn more about verify method of scilla. 
[ZIlliqa Schnorr Test.pdf](https://github.com/zilpay/zil-pay/files/7072415/ZIlliqa.Schnorr.Test.pdf)
