### ISSUE TITLE
Printing seed button prints blank

### ISSUE THREAD

**Issue by noel-yoo** [zilpay/zil-pay#51]
**Describe the bug**
Printing seed button prints blank.

**To Reproduce**

0. Open FF
1. Click Create
2. Click Print
3. See the blank page

https://user-images.githubusercontent.com/86328181/133015018-80783acd-5a27-4309-9f2e-92703892a25f.mov

**Possible Solution**
https://github.com/zilpay/zil-pay/blob/0fc15823b00ce3c36186c027a081a8fa01b3b299/src/mixins/printer.js#L112-L114

You may want to use `win.document.write` 

e.g.
```
win.document.write("<p>This is 'MsgWindow'. I am 200px wide and 100px tall!</p>"); 
 ```
Reference: https://www.w3schools.com/jsref/met_win_open.asp

**Expected behavior**
Should be able to print seed.

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Browser: Firefox 
 - Version: 92.0 (64-bit)

**Comment by hicaru** [comment]
thanks for your issue, i will fix it on new release.
