### ISSUE TITLE
Sometimes users can get confused with the multiple windows

### ISSUE THREAD

**Issue by noel-yoo** [zilpay/zil-pay#52]
**Is your feature request related to a problem? Please describe.**

https://github.com/Zilliqa/neo-savant/issues/123 is a case where a user can get confused with the UI:

*A case where Alice get confused with multiple windows:*
1. Alice sets gas limit `1` and tries to deploy a contract to see it fails by opening a window (`w1`).
2. Alice notices the error message `Gas limit(1) lower than minimum for creating contract (1163)`
3. Alice clicks the outside of w1 and doesn't close it
4. Alice sets the gas price to `2500` and tries to deploy a contract to see it succeeded by opening a window (`w2`).
5. Alice sees the previous window without the error message `Gas limit(1) lower than minimum for creating contract (1163)`
5. Alice thinks the gas limit is reverted to previous value in `w2`.

*What happened actually:*
We know that actually the `w2` window just was closed and the `w1` is being displayed.
 
Here is the screen recording which can elaborate the above confusion.
https://github.com/Zilliqa/neo-savant/issues/123#issuecomment-925485405

*Key Question:*
Is there any good solution to prevent this kind of confusion?

**Comment by hicaru** [comment]
Hello thanks for your issue, now Zilliqa have no API for calculate gasLimit

**Comment by hicaru** [comment]
fixed in 1.0.0 version
