### ISSUE TITLE
Extra protection on transactions

### ISSUE THREAD

**Issue by bugatsinho** [zilpay/zil-pay#54]
**Is your feature request related to a problem? Please describe.**
My suggestion is to protect funds from scammers that use telegram etc and ask from users to connect their wallets to a website and then they get access to their wallets and rob the funds.

**Describe the solution you'd like**
My recommendation is to add a second validator (mobile or the use of the password that we write to access the wallet) for transactions. so scammers even when they have access to our wallets can't make the transfers without the second validator.

**Describe alternatives you've considered**

**Additional context**
Lately 23days ago i lost all my zilliqa holdings and other tokens that i have in this address
https://viewblock.io/zilliqa/address/zil1ecm3r6aeqknczzadg69f6afzdtvzt0p77pkysa

it was totally my fault for this but i'm not the only one. 
Here the wallet of the scammer
https://viewblock.io/zilliqa/address/zil14axw4mp2665j5rlyvs48sd4ssceypezyk9q036

LET'S SAFU

**Comment by hicaru** [comment]
Hello we will add this address to scam list. thanks for your issue

**Comment by bugatsinho** [comment]
thank you for your reply. By adding the address to a scam list is ok but not the solution. Maybe my recommendation is way more complicated that i think but as many exchanges use extra protection on withdraws i though that adding only the wallet password to withdraws will solve the problem when someone takes  control of the wallet right? 
thank you again!
