### ISSUE TITLE
Zilpay wallet can not import hardware wallet Ledger in Brave, Chrom and Firefox

### ISSUE THREAD

**Issue by XH9981** [zilpay/zil-pay#55]
**Describe the bug**
Zilpay wallet can not import hardware wallet Ledger in Brave, Chrom and Firefox in Windows 10

**To Reproduce**
1. Log in the Zilpay wallet
2. Click on 'Accounts'
3. Click 'Add', select 'Ledger', then click 'import'
4. Ledger hard wallet not response. See error 'U2F timeout'

**Expected behavior**
 Ledger hard wallet not response. See error 'U2F timeout'

**Screenshots**

**Desktop (please complete the following information):**
![Capture error message 1](https://user-images.githubusercontent.com/93766415/140494839-db75ad46-8174-4f3d-b3d3-3fc55c7bf63c.JPG)

 - OS: Windows 10
 - Browser Chrom, Brave, Firefox
 -Ledger firmwar version: 2.0.0

**Comment by harrinho84** [comment]
Have the exact same issue in Mac OS, although I don't think the OS matters anyway. I sometimes get the "Get Address" code in my ledger but nothing happens

**Comment by buyer27sg** [comment]
I have the exact same issue with Chrome, using Mac OS.

**Comment by buyer27sg** [comment]
Tried again, same problem using windows
