### ISSUE TITLE
ZilPay 1.0.0 + Firefox 94.0 breaking

### ISSUE THREAD

**Issue by jsarcher** [zilpay/zil-pay#63]
ZilPay 1.0.0 + Firefox 94.0 does not allow signing transactions. The same issue was observed with ZilPay 0.9.9.

Error using ZilPay Ledger Wallet: "Unable to verify transaction"
![verify_tx](https://user-images.githubusercontent.com/7070742/144585202-fc901c6e-2204-4aaa-ad55-4bbbac18a9b0.png)

Error using ZilPay Browser Wallet: "WEBHID is not supported"
![webhid](https://user-images.githubusercontent.com/7070742/144584740-e64c07c5-f9cb-4ee4-b2be-44e12504469e.png)

**Comment by hicaru** [comment]
hello, what the ledger version have you installed?

**Comment by jsarcher** [comment]
Zilliqa Ledger App 0.4.3

**Comment by jsarcher** [comment]
The issue has been resolved by upgrading Ledger Firmware to v2.0.0 and Zilliqa Ledger App 0.4.4 

Thanks!
