### ISSUE TITLE
not able to add XSGD as custom token

### ISSUE THREAD

**Issue by spngspng** [zilpay/zil-pay#66]
not able to add XSGD as custom token zil180v66mlw007ltdv8tq5t240y7upwgf7djklmwh

error message is contact_owner is required

**Comment by spngspng** [comment]
other token like XCAD, ZWAP can be added without any problem.  only XSGD cannot

**Comment by hicaru** [comment]
hello you adding incorrect address! You should add proxy address

**Comment by spngspng** [comment]
what is the correct address to add?
