### ISSUE TITLE
Zillpay wallet problem

### ISSUE THREAD

**Issue by Amentinho** [zilpay/zil-pay#70]
Hello,
My laptop broke so I needed to get a new one. I'm trying to recover my zillpay wallet with my recovery phrase, but gives me a new wallet id. It is not recovering my previous one.

My phrase is correct and I only had one zilliqa address before, so there is no way I'm doing it wrongly.

Do you know how can solve it? I know my old wallet id as I made transactions, but there is no way to recover the wallet by first inputting it and then putting the recovery phrase.
Thank you,
AA

**Comment by hicaru** [comment]
hello you have only one way to remember correct words, if you made a mistake in any char or word, it shows incorrect accounts
